// Generated by CoffeeScript 1.9.3
var AddXAxis, basic_num_format, comma_num_format, k_num_format, percent_num_format, process_data, total_obs;

total_obs = 16247;

basic_num_format = d3.format(".0f");

k_num_format = d3.format("s");

percent_num_format = d3.format(",.1%");

comma_num_format = d3.format(",0f");

process_data = function(d) {
  var data;
  data = {
    birth: +d.birth,
    entrepreneur: +d.entrepreneur,
    founder: +d.founder,
    early_emp: +d.early_emp,
    board_member: +d.board_member,
    investor: +d.investor,
    family_ent: +d.family_ent,
    first_venture_age: +d.first_venture_age,
    gender: d.gender,
    instate: +d.instate,
    inv_innov: d.inv_innov,
    inv_uva: d.inv_uva,
    last_deg: d.last_deg,
    last_field: d.last_field,
    last_gradyr: +d.last_gradyr,
    last_job_ind: d.last_job_ind,
    race: d.race,
    small_bus_exp: +d.small_bus_exp,
    venture_nums: +d.venture_nums,
    key_0: +d.key_0
  };
  return data;
};

AddXAxis = function(chartToUpdate, displayText) {
  return chartToUpdate.svg().append("text").attr("class", "x-axis-label").attr("text-anchor", "middle").attr("x", chartToUpdate.width() / 2).attr("y", chartToUpdate.height() - 1.5).text(displayText);
};

d3.csv('data/alum_xf.csv', process_data, function(data) {
  var chart, dim, grp, reset_all, write_stat, xf;
  xf = crossfilter(data);
  dim = {};
  dim.birth = xf.dimension(function(d) {
    return d.birth;
  });
  dim.gender = xf.dimension(function(d) {
    return d.gender;
  });
  dim.entrepreneur = xf.dimension(function(d) {
    if (d.entrepreneur === 1) {
      return "Yes";
    } else {
      return "No";
    }
  });
  dim.founder = xf.dimension(function(d) {
    if (d.founder === 1) {
      return "Yes";
    } else {
      return "No";
    }
  });
  dim.early_emp = xf.dimension(function(d) {
    if (d.early_emp === 1) {
      return "Yes";
    } else {
      return "No";
    }
  });
  dim.board_member = xf.dimension(function(d) {
    if (d.board_member === 1) {
      return "Yes";
    } else {
      return "No";
    }
  });
  dim.investor = xf.dimension(function(d) {
    if (d.investor === 1) {
      return "Yes";
    } else {
      return "No";
    }
  });
  dim.first_venture_age = xf.dimension(function(d) {
    return d.first_venture_age;
  });
  dim.family_ent = xf.dimension(function(d) {
    if (d.family_ent === 1) {
      return "Yes";
    } else {
      return "No";
    }
  });
  dim.instate = xf.dimension(function(d) {
    if (d.instate === 1) {
      return "Yes";
    } else {
      return "No";
    }
  });
  dim.inv_innov = xf.dimension(function(d) {
    if (d.inv_innov === "") {
      return "Not involved at all";
    } else {
      return d.inv_innov;
    }
  });
  dim.inv_uva = xf.dimension(function(d) {
    if (d.inv_uva === "") {
      return "Not involved at all";
    } else {
      return d.inv_uva;
    }
  });
  dim.last_deg = xf.dimension(function(d) {
    if (d.last_deg === "") {
      return "No information";
    } else {
      return d.last_deg;
    }
  });
  dim.last_field = xf.dimension(function(d) {
    if (d.last_field === "") {
      return "No information";
    } else {
      return d.last_field;
    }
  });
  dim.race = xf.dimension(function(d) {
    return d.race;
  });
  dim.small_bus_exp = xf.dimension(function(d) {
    if (d.small_bus_exp === 1) {
      return "Yes";
    } else {
      return "No";
    }
  });
  dim.venture_nums = xf.dimension(function(d) {
    return d.venture_nums;
  });
  grp = {};
  grp.entrepreneur = dim.entrepreneur.group();
  grp.founder = dim.founder.group();
  grp.early_emp = dim.early_emp.group();
  grp.board_member = dim.board_member.group();
  grp.investor = dim.investor.group();
  grp.gender = dim.gender.group();
  grp.race = dim.race.group();
  grp.instate = dim.instate.group();
  grp.birth = dim.birth.group(function(d) {
    return Math.floor(d / 5) * 5;
  });
  grp.first_venture_age = dim.first_venture_age.group(function(d) {
    return Math.floor(d / 5) * 5;
  });
  grp.small_bus_exp = dim.small_bus_exp.group();
  grp.family_ent = dim.family_ent.group();
  grp.inv_innov = dim.inv_innov.group();
  grp.inv_uva = dim.inv_uva.group();
  grp.last_deg = dim.last_deg.group();
  grp.last_field = dim.last_field.group();
  grp.venture_nums = dim.venture_nums.group();
  chart = {};
  chart.founderPie = dc.pieChart('#founder');
  chart.earlyempPie = dc.pieChart('#early-emp');
  chart.investorPie = dc.pieChart("#investor");
  chart.boardMemberPie = dc.pieChart("#board-member");
  chart.entrepreneurPie = dc.pieChart('#entrepreneur');
  chart.genderPie = dc.pieChart('#gender');
  chart.instatePie = dc.pieChart('#instate');
  chart.raceRow = dc.rowChart('#race');
  chart.birthBar = dc.barChart('#birth');
  chart.firstVentureBar = dc.barChart("#first-venture");
  chart.smallBusPie = dc.pieChart('#small-bus-exp');
  chart.familyEntPie = dc.pieChart("#family-ent");
  chart.invInnovRow = dc.rowChart('#inv-innov');
  chart.invUvaRow = dc.rowChart('#inv-uva');
  chart.lastDegRow = dc.rowChart('#last-deg');
  chart.lastFieldRow = dc.rowChart('#last-field');
  chart.numVentRow = dc.rowChart('#num-vent');
  chart.founderPie.width(150).height(150).radius(75).dimension(dim.founder).group(grp.founder).label(function(d) {
    return d.data.key + " " + (Math.round((d.endAngle - d.startAngle) / Math.PI * 50)) + "%";
  });
  chart.earlyempPie.width(150).height(150).radius(75).dimension(dim.early_emp).group(grp.early_emp).label(function(d) {
    return d.data.key + " " + (Math.round((d.endAngle - d.startAngle) / Math.PI * 50)) + "%";
  });
  chart.investorPie.width(150).height(150).radius(75).dimension(dim.investor).group(grp.investor).label(function(d) {
    return d.data.key + " " + (Math.round((d.endAngle - d.startAngle) / Math.PI * 50)) + "%";
  });
  chart.boardMemberPie.width(150).height(150).radius(75).dimension(dim.board_member).group(grp.board_member).label(function(d) {
    return d.data.key + " " + (Math.round((d.endAngle - d.startAngle) / Math.PI * 50)) + "%";
  });
  chart.entrepreneurPie.width(200).height(200).radius(100).dimension(dim.entrepreneur).group(grp.entrepreneur).label(function(d) {
    return d.data.key + " " + (Math.round((d.endAngle - d.startAngle) / Math.PI * 50)) + "%";
  });
  chart.genderPie.width(200).height(200).radius(100).dimension(dim.gender).group(grp.gender).label(function(d) {
    return d.data.key + " " + (Math.round((d.endAngle - d.startAngle) / Math.PI * 50)) + "%";
  });
  chart.instatePie.width(200).height(200).radius(100).dimension(dim.instate).group(grp.instate).label(function(d) {
    return d.data.key + " " + (Math.round((d.endAngle - d.startAngle) / Math.PI * 50)) + "%";
  });
  chart.raceRow.width(550).height(200).dimension(dim.race).group(grp.race).elasticX(true).cap(5).othersGrouper(false).colors(d3.scale.category10()).xAxis().tickFormat(function(v) {
    return k_num_format(v);
  });
  chart.birthBar.width(500).height(250).dimension(dim.birth).group(grp.birth).x(d3.scale.linear().domain([1930, 1995])).xUnits(function() {
    return 13;
  }).elasticY(true).renderHorizontalGridLines(true).renderVerticalGridLines(true).margins({
    top: 20,
    right: 20,
    bottom: 30,
    left: 50
  }).xAxis().tickFormat(function(v) {
    return basic_num_format(v);
  });
  chart.firstVentureBar.width(450).height(250).dimension(dim.first_venture_age).group(grp.first_venture_age).x(d3.scale.linear().domain([15, 75])).xUnits(function() {
    return 12;
  }).elasticY(true).renderHorizontalGridLines(true).renderVerticalGridLines(true).margins({
    top: 20,
    right: 20,
    bottom: 30,
    left: 50
  });
  chart.smallBusPie.width(200).height(200).radius(100).dimension(dim.small_bus_exp).group(grp.small_bus_exp).label(function(d) {
    return d.data.key + " " + (Math.round((d.endAngle - d.startAngle) / Math.PI * 50)) + "%";
  });
  chart.familyEntPie.width(150).height(150).radius(75).dimension(dim.family_ent).group(grp.family_ent).label(function(d) {
    return d.data.key + " " + (Math.round((d.endAngle - d.startAngle) / Math.PI * 50)) + "%";
  });
  chart.invUvaRow.width(400).height(180).dimension(dim.inv_uva).group(grp.inv_uva).elasticX(true).colors(d3.scale.category10()).xAxis().tickFormat(function(v) {
    return k_num_format(v);
  });
  chart.invInnovRow.width(400).height(180).dimension(dim.inv_innov).group(grp.inv_innov).elasticX(true).colors(d3.scale.category10()).xAxis().tickFormat(function(v) {
    return k_num_format(v);
  });
  chart.lastDegRow.width(500).height(300).dimension(dim.last_deg).group(grp.last_deg).elasticX(true).xAxis().tickFormat(function(v) {
    return k_num_format(v);
  });
  chart.lastFieldRow.width(500).height(300).dimension(dim.last_field).group(grp.last_field).elasticX(true).cap(8).xAxis().tickFormat(function(v) {
    return k_num_format(v);
  });
  chart.numVentRow.width(400).height(200).dimension(dim.venture_nums).group(grp.venture_nums).elasticX(true).cap(4).othersLabel("More").colors(d3.scale.category10()).xAxis().tickFormat(function(v) {
    return k_num_format(v);
  });
  dc.renderAll();
  reset_all = function() {
    dc.filterAll();
    return dc.redrawAll();
  };
  $(".reset-all").click(reset_all);
  $("#reset-first-venture").click(function() {
    chart.firstVentureBar.filterAll();
    return dc.redrawAll();
  });
  $("#reset-birth").click(function() {
    chart.birthBar.filterAll();
    return dc.redrawAll();
  });
  $("#reset-race").click(function() {
    chart.raceRow.filterAll();
    return dc.redrawAll();
  });
  $("#reset-inv-uva").click(function() {
    chart.invUvaRow.filterAll();
    return dc.redrawAll();
  });
  $("#reset-inv-innov").click(function() {
    chart.invInnovRow.filterAll();
    return dc.redrawAll();
  });
  $("#reset-last-deg").click(function() {
    chart.lastDegRow.filterAll();
    return dc.redrawAll();
  });
  $("#reset-last-field").click(function() {
    chart.lastFieldRow.filterAll();
    return dc.redrawAll();
  });
  $("#reset-num-vent").click(function() {
    chart.numVentRow.filterAll();
    return dc.redrawAll();
  });
  write_stat = function() {
    var selected_num;
    selected_num = xf.groupAll().reduceCount().value();
    return $('#stat').text((comma_num_format(selected_num)) + " selected of " + (comma_num_format(total_obs)) + " | " + (percent_num_format(selected_num / total_obs)));
  };
  chart.founderPie.on("filtered", write_stat);
  chart.earlyempPie.on("filtered", write_stat);
  chart.investorPie.on("filtered", write_stat);
  chart.boardMemberPie.on("filtered", write_stat);
  chart.entrepreneurPie.on("filtered", write_stat);
  chart.genderPie.on("filtered", write_stat);
  chart.instatePie.on("filtered", write_stat);
  chart.raceRow.on("filtered", write_stat);
  chart.birthBar.on("filtered", write_stat);
  chart.firstVentureBar.on("filtered", write_stat);
  chart.smallBusPie.on("filtered", write_stat);
  chart.familyEntPie.on("filtered", write_stat);
  chart.invInnovRow.on("filtered", write_stat);
  chart.invUvaRow.on("filtered", write_stat);
  chart.lastDegRow.on("filtered", write_stat);
  chart.lastFieldRow.on("filtered", write_stat);
  return chart.numVentRow.on("filtered", write_stat);
});
