// Generated by CoffeeScript 1.9.3
var processData;

processData = function(d) {
  var data;
  data = {
    birth: +d.birth,
    entrepreneur: +d.entrepreneur,
    founder: +d.founder,
    early_emp: +d.early_emp,
    board_member: +d.board_member,
    investor: +d.investor,
    family_ent: +d.family_ent,
    first_fd_age: +d.first_fd_age,
    gender: d.gender,
    instate: +d.instate,
    inv_innov: d.inv_innov,
    inv_uva: d.inv_uva,
    last_deg: d.last_deg,
    last_field: d.last_field,
    last_gradyr: +d.last_gradyr,
    last_job_ind: d.last_job_ind,
    race: d.race,
    resistat: d.resistat,
    small_bus_exp: +d.small_bus_exp,
    venture_nums: +d.venture_nums,
    key_0: +d.key_0
  };
  return data;
};

d3.csv('data/alum_xf.csv', processData, function(data) {
  var dim;
  data = crossfilter(data);
  dim = {};
  dim.birth = data.dimension(function(d) {
    return d.birth;
  });
  dim.entrepreneur = data.dimension(function(d) {
    return d.entrepreneur;
  });
  dim.founder = data.dimension(function(d) {
    return d.founder;
  });
  dim.early_emp = data.dimension(function(d) {
    return d.early_emp;
  });
  dim.board_member = data.dimension(function(d) {
    return d.board_member;
  });
  dim.investor = data.dimension(function(d) {
    return d.investor;
  });
  dim.family_ent = data.dimension(function(d) {
    return d.family_ent;
  });
  dim.first_fd_age = data.dimension(function(d) {
    return d.first_fd_age;
  });
  dim.gender = data.dimension(function(d) {
    return d.gender;
  });
  dim.instate = data.dimension(function(d) {
    return d.instate;
  });
  dim.inv_innov = data.dimension(function(d) {
    return d.inv_innov;
  });
  dim.inv_uva = data.dimension(function(d) {
    return d.inv_uva;
  });
  dim.last_deg = data.dimension(function(d) {
    return d.last_deg;
  });
  dim.last_field = data.dimension(function(d) {
    return d.last_field;
  });
  dim.race = data.dimension(function(d) {
    return d.race;
  });
  dim.resistat = data.dimension(function(d) {
    return d.resistat;
  });
  dim.small_bus_exp = data.dimension(function(d) {
    return d.small_bus_exp;
  });
  return dim.venture_nums = data.dimension(function(d) {
    return d.venture_nums;
  });
});
